### ISSUE TITLE
Créer les wireframes

### ISSUE THREAD

**Issue by FredericFouche** [JrmLg/Simple-Sequelize-Dashboard#3]
Créer les wireframes des pages/composants des features suivantes :

- Page de Login
- Page de Logout
- Affichage des models
- Panneau d'administration

**Comment by Theophile-Dcn** [comment]
Saluuut

**Comment by Theophile-Dcn** [comment]
![Image](https://github.com/JrmLg/Simple-Sequelize-Dashboard/assets/88760829/df8d4c60-4469-4124-ac27-e0bd018039b8)
![Image](https://github.com/JrmLg/Simple-Sequelize-Dashboard/assets/88760829/8b6b13f6-5e3d-4e42-8d01-b44e1bee1c30)
![Image](https://github.com/JrmLg/Simple-Sequelize-Dashboard/assets/88760829/c44d425f-e531-4b43-bf05-1a086877f93f)
