### ISSUE TITLE
Intégration model adminUser/adminRole/adminPermission

### ISSUE THREAD

**Issue by FredericFouche** [JrmLg/Simple-Sequelize-Dashboard#4]
Création des models de base du dashboard adminUser, adminRole, adminPermission

**Comment by JrmLg** [comment]
![image](https://github.com/JrmLg/Simple-Sequelize-Dashboard/assets/63566435/2eab93d2-0b55-4312-9f01-992b9279a1b1)

Une représentation simplifié des tables pour la gestion d'administration.

**Comment by FredericFouche** [comment]
Model de base fonctionnel dispo sur le commit :  81e9825

merge Ok avec la main
